In [107]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [108]:
# loading dataset
data = pd.read_excel(r"C:\Users\user\Downloads\iris (1).xls")

In [109]:
data.head()

SL   SW   PL   PW Classification
0  5.1  3.5  1.4  0.2    Iris-setosa
1  4.9  3.0  1.4  0.2    Iris-setosa
2  NaN  3.2  1.3  0.2    Iris-setosa
3  4.6  3.1  1.5  0.2    Iris-setosa
4  5.0  3.6  1.4  0.2    Iris-setosa

# Data Preprocessing

In [111]:
data.isna().sum()

SL                7
SW                6
PL                6
PW                0
Classification    0
dtype: int64

In [112]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   SL              143 non-null    float64
 1   SW              144 non-null    float64
 2   PL              144 non-null    float64
 3   PW              150 non-null    float64
 4   Classification  150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [113]:
data.columns

Index(['SL', 'SW', 'PL', 'PW', 'Classification'], dtype='object')

In [114]:
for i in ['SL', 'SW', 'PL']:
    data[i] = data[i].fillna(data[i].median())

In [115]:
data.isna().sum()

SL                0
SW                0
PL                0
PW                0
Classification    0
dtype: int64

# Encoding

In [117]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

In [118]:
data['Classification'] = label_encoder.fit_transform(data['Classification'])

In [119]:
data.head(10)

SL   SW   PL   PW  Classification
0  5.1  3.5  1.4  0.2               0
1  4.9  3.0  1.4  0.2               0
2  5.8  3.2  1.3  0.2               0
3  4.6  3.1  1.5  0.2               0
4  5.0  3.6  1.4  0.2               0
5  5.4  3.9  1.7  0.4               0
6  4.6  3.4  1.4  0.3               0
7  5.0  3.4  1.5  0.2               0
8  4.4  2.9  1.4  0.2               0
9  4.9  3.1  1.5  0.1               0

In [120]:
x = data.drop('Classification', axis = 1)

In [121]:
y = data['Classification']

# Scailing

In [123]:
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()


In [124]:
x

SL   SW    PL   PW
0    5.1  3.5  1.40  0.2
1    4.9  3.0  1.40  0.2
2    5.8  3.2  1.30  0.2
3    4.6  3.1  1.50  0.2
4    5.0  3.6  1.40  0.2
..   ...  ...   ...  ...
145  6.7  3.0  5.20  2.3
146  6.3  2.5  5.00  1.9
147  6.5  3.0  4.35  2.0
148  6.2  3.4  5.40  2.3
149  5.9  3.0  5.10  1.8

[150 rows x 4 columns]

In [125]:
x = std_scaler.fit_transform(x)

In [126]:
type(x)

numpy.ndarray

In [127]:
x = pd.DataFrame(x)

In [128]:
x.columns = ['SL','SW','PL','PW']

In [129]:
x.head()

SL        SW        PL        PW
0 -0.934811  1.076275 -1.380791 -1.312977
1 -1.182990 -0.112541 -1.380791 -1.312977
2 -0.066181  0.362985 -1.438808 -1.312977
3 -1.555260  0.125222 -1.322775 -1.312977
4 -1.058900  1.314038 -1.380791 -1.312977

In [130]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state = 42)

# Logistic Regression

In [132]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg =log_reg.fit(x_train,y_train)


In [133]:
y_pred = log_reg.predict(x_test)

In [134]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

In [226]:
print('Accuracy is : ',accuracy_score(y_test,y_pred))
print('confusion matrix is : ',confusion_matrix(y_test,y_pred))
print('precision_score is : ',precision_score(y_test,y_pred, average = 'macro'))
print('Recall is : ',recall_score(y_test,y_pred, average = 'macro'))
print('F1 Score is : ',f1_score(y_test,y_pred, average = 'macro'))

Accuracy is :  1.0
confusion matrix is :  [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
precision_score is :  1.0
Recall is :  1.0
F1 Score is :  1.0


# Decision Tree

In [137]:
from sklearn.tree import DecisionTreeClassifier

In [138]:
dt_cls = DecisionTreeClassifier()
dtcls = dt_cls.fit(x_train,y_train)
y_pred_dt = dt_cls.predict(x_test)

In [232]:
print('Accuracy is : ',accuracy_score(y_test,y_pred_dt))
print('Precision is : ',precision_score(y_test,y_pred_dt,average='macro'))
print('Recall is : ',recall_score(y_test,y_pred_dt,average = 'macro'))
print('F1 Score is : ',f1_score(y_test,y_pred_dt,average = 'macro'))
print('confusion matrix is : ',confusion_matrix(y_test,y_pred_dt))

Accuracy is :  0.9555555555555556
Precision is :  0.9555555555555556
Recall is :  0.9487179487179488
F1 Score is :  0.9484126984126983
confusion matrix is :  [[19  0  0]
 [ 0 11  2]
 [ 0  0 13]]


# Random Forest

In [143]:
from sklearn.ensemble import RandomForestClassifier

In [144]:
rf_cls = RandomForestClassifier()
rfcls = rf_cls.fit(x_train,y_train)
y_pred_rf = rf_cls.predict(x_test)

In [234]:
print('Accuracy is : ',accuracy_score(y_test,y_pred_rf))
print('Precision is : ',precision_score(y_test,y_pred_rf,average='macro'))
print('Recall is : ',recall_score(y_test,y_pred_rf,average = 'macro'))
print('F1 Score is : ',f1_score(y_test,y_pred_rf,average = 'macro'))
print('confusion matrix is : ',confusion_matrix(y_test,y_pred_rf))

Accuracy is :  1.0
Precision is :  1.0
Recall is :  1.0
F1 Score is :  1.0
confusion matrix is :  [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


# K-NN

In [149]:
from sklearn.neighbors import KNeighborsClassifier

In [150]:
metric_k = []
neighbors = np.arange(3,15) # k value is 3 upto 14

In [151]:
for k in neighbors:
    classifier = KNeighborsClassifier(n_neighbors = k, metric = 'euclidean')
    classifier.fit(x_train,y_train)
    y_predictions = classifier.predict(x_test)
    acc = accuracy_score(y_test,y_predictions)
    metric_k.append(acc)

In [152]:
metric_k

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

In [153]:
classifier = KNeighborsClassifier(n_neighbors = 7, metric = 'euclidean')
classifier.fit(x_train,y_train)
y_predictions = classifier.predict(x_test)

In [236]:
print('Accuracy is :',accuracy_score(y_test,y_predictions))
print('Precision is :',precision_score(y_test,y_predictions, average = 'macro'))
print('Recall is : ',recall_score(y_test,y_predictions,average = 'macro'))
print('F1 Score is : ',f1_score(y_test,y_predictions,average = 'macro'))
print('confusion matrix is : ',confusion_matrix(y_test,y_predictions))

Accuracy is : 1.0
Precision is : 1.0
Recall is :  1.0
F1 Score is :  1.0
confusion matrix is :  [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


# Naive Bayes

In [157]:
from sklearn.naive_bayes import GaussianNB

In [158]:
nb_classifier = GaussianNB()
nb_classifier.fit(x_train,y_train)

GaussianNB()

In [159]:
y_pred = nb_classifier.predict(x_test)

In [239]:
print('Accuracy is : ',accuracy_score(y_test,y_pred))
print('Precision is : ',precision_score(y_test,y_pred , average = 'macro'))
print('Recall is : ',recall_score(y_test,y_pred,average = 'macro'))
print('F1 Score is : ',f1_score(y_test,y_pred,average = 'macro'))
print('confusion matrix is : ',confusion_matrix(y_test,y_pred))

Accuracy is :  1.0
Precision is :  1.0
Recall is :  1.0
F1 Score is :  1.0
confusion matrix is :  [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


# SVM 

In [163]:
from sklearn.svm import SVC

In [214]:
svm_cls = SVC(kernel = 'linear')
svm_cls = svm_cls.fit(x_train,y_train)

In [216]:
y_pred_svm = svm_cls.predict(x_test)

In [218]:
confusion_matrix(y_test,y_pred_svm)

array([[19,  0,  0],
       [ 0, 12,  1],
       [ 0,  0, 13]], dtype=int64)

In [220]:
accuracy_score(y_test,y_pred_svm)

0.9777777777777777

In [224]:
precision_score(y_test,y_pred_svm,average = 'macro')

0.9761904761904763

Here Logistic Regression,Random Forest, Naive Bayes and K-NN gives best result.